### ISSUE TITLE
Bug：控制台报错“linkOnBlackPage  is not defined”导致文章目录不可见

### ISSUE THREAD

**Issue by dliceya** [CodeLunatic/halo-theme-simple-bootstrap#33]
昨天晚上重装完博客发现没有目录了，我以为是自己把哪里改坏了，然后我今天重现安装了博客，重现clone的主题，发现还是这个问题，可以帮忙看一下吗？
linkOnBlackPage这个变量是干嘛的，具体的信息如下：

jQuery.Deferred exception: linkOnBlackPage is not defined ReferenceError: linkOnBlackPage is not defined
    at HTMLDocument.<anonymous> (https://www.dlice.xyz/themes/codelunatic_simple/source/js/post.js:371:5)
    at e (https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js:2:29453)
    at t (https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js:2:29755) undefined

Uncaught ReferenceError: linkOnBlackPage is not defined
    at HTMLDocument.<anonymous> (post.js:371)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)

**Comment by dliceya** [comment]
https://www.dlice.xyz/?p=1 错误博客
